import {
  AdminBadgeIcon,
  AdminIcon,
  AlignCenterIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AnalyticsIcon,
  AnnouncementIcon,
  AttachmentIcon,
  AudioFillIcon,
  AudioIcon,
  AudioRectFillIcon,
  AudioRectIcon,
  BackIcon,
  BagAddIcon,
  BagFillIcon,
  BagIcon,
  BagRemoveIcon,
  BankIcon,
  BatteryBoltIcon,
  BatteryFillIcon,
  BatteryIcon,
  BoltCircleIcon,
  BoltDocsIcon,
  BoltIcon,
  BriefcaseIcon,
  BugFillIcon,
  BugIcon,
  CardAddIcon,
  CardIcon,
  ChannelIcon,
  ChannelPrivateIcon,
  ChannelsIcon,
  CheckBoxIcon,
  CheckMarkIcon,
  ClockFillIcon,
  ClockIcon,
  CloudDownloadIcon,
  CloudIcon,
  CloudUploadIcon,
  CodeIcon,
  CommunityIcon,
  CompassIcon,
  ControlsIcon,
  CopyCheckIcon,
  CopyIcon,
  CrosshairsIcon,
  DeleteIcon,
  DocsFillIcon,
  DocsIcon,
  DoorEnterIcon,
  DoorLeaveIcon,
  DownCaretIcon,
  DownFillIcon,
  DownIcon,
  EditIcon,
  EmailFillIcon,
  EmailIcon,
  EmbedIcon,
  EmojiIcon,
  EnterIcon,
  EventAddIcon,
  EventCancelIcon,
  EventCheckIcon,
  EventCodeIcon,
  EventLikeIcon,
  EventMoveIcon,
  EverythingIcon,
  ExpandIcon,
  ExploreIcon,
  ExternalFillIcon,
  ExternalIcon,
  FacebookFillIcon,
  FacebookIcon,
  FigmaFillIcon,
  FigmaIcon,
  FilterFillIcon,
  FilterIcon,
  FlagFillIcon,
  FlagIcon,
  FoodIcon,
  ForbiddenIcon,
  ForwardIcon,
  FreezeIcon,
  FriendIcon,
  GithubFillIcon,
  GithubIcon,
  GoogleFillIcon,
  GoogleIcon,
  GridIcon,
  HelpIcon,
  HistoryIcon,
  HolderIcon,
  HomeIcon,
  IdeaIcon,
  ImportantFillIcon,
  ImportantIcon,
  InfoIcon,
  InserterIcon,
  InstagramFillIcon,
  InstagramIcon,
  LeaderIcon,
  LikeFillIcon,
  LikeIcon,
  LinkIcon,
  ListIcon,
  MapAppIcon,
  MapPinIcon,
  MarkdownIcon,
  MediumFillIcon,
  MediumIcon,
  MegaphoneFillIcon,
  MegaphoneIcon,
  MehIcon,
  MemberAddIcon,
  MemberRemoveIcon,
  MentionIcon,
  MenuIcon,
  MessageFillIcon,
  MessageIcon,
  MessageNewIcon,
  MessageSimpleFillIcon,
  MessageSimpleIcon,
  MessageSimpleNewIcon,
  MessengerFillIcon,
  MessengerIcon,
  MicIcon,
  MinusFillIcon,
  MinusIcon,
  MoonFillIcon,
  MoonIcon,
  MoreFillIcon,
  MoreIcon,
  MoreVerticalIcon,
  MuteIcon,
  NotificationFillIcon,
  NotificationIcon,
  PaymentDocsIcon,
  PaymentIcon,
  PaymentTransferIcon,
  PersonCardIcon,
  PersonIcon,
  PhoneBoltIcon,
  PhoneIcon,
  PhoneVibrateIcon,
  PhotoFillIcon,
  PhotoIcon,
  PinFillIcon,
  PinIcon,
  PlusFillIcon,
  PlusIcon,
  PositionBottomIcon,
  PositionBottomLeftIcon,
  PositionBottomRightIcon,
  PositionCenterIcon,
  PositionLeftIcon,
  PositionRightIcon,
  PositionTopIcon,
  PositionTopLeftIcon,
  PositionTopRightIcon,
  PostCancelIcon,
  PostFillIcon,
  PostIcon,
  PrivateIcon,
  PrivateOutlineIcon,
  PrivateUnlockedIcon,
  ProfileFillIcon,
  ProfileIcon,
  QuoteIcon,
  RelaxedIcon,
  RepIcon,
  ReplyIcon,
  RightCaretIcon,
  RssIcon,
  SadIcon,
  SamIcon,
  SearchIcon,
  SendFillIcon,
  SendIcon,
  SettingsIcon,
  ShareIcon,
  ShirtFillIcon,
  ShirtIcon,
  SlackFillIcon,
  SlackIcon,
  SortAscIcon,
  SortDescIcon,
  StickerIcon,
  SupportFillIcon,
  SupportIcon,
  TerminalIcon,
  ThreadIcon,
  ThumbsDownFillIcon,
  ThumbsDownIcon,
  ThumbsUpFillIcon,
  ThumbsUpIcon,
  TransactionsIcon,
  TvFillIcon,
  TvIcon,
  TwitchFillIcon,
  TwitchIcon,
  TwitchNudeIcon,
  TwitterFillIcon,
  TwitterIcon,
  UpCaretIcon,
  UpFillIcon,
  UpIcon,
  ViewBackIcon,
  ViewCloseIcon,
  ViewCloseSmallIcon,
  ViewFillIcon,
  ViewForwardIcon,
  ViewHideIcon,
  ViewIcon,
  ViewReloadIcon,
  WebIcon,
  WelcomeIcon,
  WifiIcon,
  XFillIcon,
  XIcon,
  YoutubeFillIcon,
  YoutubeIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from 'lolicon'

export const Icons = [
  { name: 'Admin', icon: AdminIcon },
  { name: 'Admin Badge', icon: AdminBadgeIcon },
  { name: 'Align Center', icon: AlignCenterIcon },
  { name: 'Align Left', icon: AlignLeftIcon },
  { name: 'Align Right', icon: AlignRightIcon },
  { name: 'Analytics', icon: AnalyticsIcon },
  { name: 'Announcement', icon: AnnouncementIcon },
  { name: 'Attachment', icon: AttachmentIcon },
  { name: 'Audio', icon: AudioIcon },
  { name: 'AudioFill', icon: AudioFillIcon },
  { name: 'AudioRect', icon: AudioRectIcon },
  { name: 'AudioRectFill', icon: AudioRectFillIcon },
  { name: 'Back', icon: BackIcon },
  { name: 'Bag', icon: BagIcon },
  { name: 'Bag Add', icon: BagAddIcon },
  { name: 'Bag Fill', icon: BagFillIcon },
  { name: 'Bag Remove', icon: BagRemoveIcon },
  { name: 'Bank', icon: BankIcon },
  { name: 'Battery', icon: BatteryIcon },
  { name: 'Batte ry Bolt', icon: BatteryBoltIcon },
  { name: 'Battery Fill', icon: BatteryFillIcon },
  { name: 'Bolt', icon: BoltIcon },
  { name: 'MoreVertical', icon: MoreVerticalIcon },
  { name: 'Holder', icon: HolderIcon },
  { name: 'Megaphone', icon: MegaphoneIcon },
  { name: 'Megaphone Fill', icon: MegaphoneFillIcon },
  { name: 'Mic', icon: MicIcon },
  { name: 'Bolt Circle', icon: BoltCircleIcon },
  { name: 'Bolt Docs', icon: BoltDocsIcon },
  { name: 'Briefcase', icon: BriefcaseIcon },
  { name: 'Bug', icon: BugIcon },
  { name: 'Bug Fill', icon: BugFillIcon },
  { name: 'Card', icon: CardIcon },
  { name: 'Card Add', icon: CardAddIcon },
  { name: 'Channel', icon: ChannelIcon },
  { name: 'Channel Private', icon: ChannelPrivateIcon },
  { name: 'Channels', icon: ChannelsIcon },
  { name: 'Check Box', icon: CheckBoxIcon },
  { name: 'Check Mark', icon: CheckMarkIcon },
  { name: 'Clock', icon: ClockIcon },
  { name: 'Clock Fill', icon: ClockFillIcon },
  { name: 'Cloud', icon: CloudIcon },
  { name: 'Cloud Download', icon: CloudDownloadIcon },
  { name: 'Cloud Upload', icon: CloudUploadIcon },
  { name: 'Code', icon: CodeIcon },
  { name: 'Community', icon: CommunityIcon },
  { name: 'Compass', icon: CompassIcon },
  { name: 'Controls', icon: ControlsIcon },
  { name: 'Copy', icon: CopyIcon },
  { name: 'Copy Check', icon: CopyCheckIcon },
  { name: 'Crosshairs', icon: CrosshairsIcon },
  { name: 'Delete', icon: DeleteIcon },
  { name: 'Docs', icon: DocsIcon },
  { name: 'Docs Fill', icon: DocsFillIcon },
  { name: 'Door Enter', icon: DoorEnterIcon },
  { name: 'Door Leave', icon: DoorLeaveIcon },
  { name: 'Down', icon: DownIcon },
  { name: 'Down Caret', icon: DownCaretIcon },
  { name: 'Down Fill', icon: DownFillIcon },
  { name: 'Edit', icon: EditIcon },
  { name: 'Email', icon: EmailIcon },
  { name: 'Email Fill', icon: EmailFillIcon },
  { name: 'Embed', icon: EmbedIcon },
  { name: 'Emoji', icon: EmojiIcon },
  { name: 'Enter', icon: EnterIcon },
  { name: 'Event Add', icon: EventAddIcon },
  { name: 'Event Cancel', icon: EventCancelIcon },
  { name: 'Event Check', icon: EventCheckIcon },
  { name: 'Event Code', icon: EventCodeIcon },
  { name: 'Event Like', icon: EventLikeIcon },
  { name: 'Event Move', icon: EventMoveIcon },
  { name: 'Everything', icon: EverythingIcon },
  { name: 'Expand', icon: ExpandIcon },
  { name: 'Explore', icon: ExploreIcon },
  { name: 'External', icon: ExternalIcon },
  { name: 'External Fill', icon: ExternalFillIcon },
  { name: 'Facebook', icon: FacebookIcon },
  { name: 'Facebook Fill', icon: FacebookFillIcon },
  { name: 'Figma', icon: FigmaIcon },
  { name: 'Figma Fill', icon: FigmaFillIcon },
  { name: 'Filter', icon: FilterIcon },
  { name: 'Filter Fill', icon: FilterFillIcon },
  { name: 'Flag', icon: FlagIcon },
  { name: 'Flag Fill', icon: FlagFillIcon },
  { name: 'Food', icon: FoodIcon },
  { name: 'Forbidden', icon: ForbiddenIcon },
  { name: 'Forward', icon: ForwardIcon },
  { name: 'Freeze', icon: FreezeIcon },
  { name: 'Friend', icon: FriendIcon },
  { name: 'Github', icon: GithubIcon },
  { name: 'Github Fill', icon: GithubFillIcon },
  { name: 'Google', icon: GoogleIcon },
  { name: 'Google Fill', icon: GoogleFillIcon },
  { name: 'Grid', icon: GridIcon },
  { name: 'Help', icon: HelpIcon },
  { name: 'History', icon: HistoryIcon },
  { name: 'Home', icon: HomeIcon },
  { name: 'Idea', icon: IdeaIcon },
  { name: 'Important', icon: ImportantIcon },
  { name: 'Important Fill', icon: ImportantFillIcon },
  { name: 'Info', icon: InfoIcon },
  { name: 'Inserter', icon: InserterIcon },
  { name: 'Instagram', icon: InstagramIcon },
  { name: 'Instagram Fill', icon: InstagramFillIcon },
  { name: 'Leader', icon: LeaderIcon },
  { name: 'Like', icon: LikeIcon },
  { name: 'Like Fill', icon: LikeFillIcon },
  { name: 'Link', icon: LinkIcon },
  { name: 'List', icon: ListIcon },
  { name: 'Map App', icon: MapAppIcon },
  { name: 'Map Pin', icon: MapPinIcon },
  { name: 'Markdown', icon: MarkdownIcon },
  { name: 'Medium', icon: MediumIcon },
  { name: 'Medium Fill', icon: MediumFillIcon },
  { name: 'Meh', icon: MehIcon },
  { name: 'Member Add', icon: MemberAddIcon },
  { name: 'Member Remove', icon: MemberRemoveIcon },
  { name: 'Mention', icon: MentionIcon },
  { name: 'Menu', icon: MenuIcon },
  { name: 'Message', icon: MessageIcon },
  { name: 'Message Fill', icon: MessageFillIcon },
  { name: 'Message New', icon: MessageNewIcon },
  { name: 'Message Simple', icon: MessageSimpleIcon },
  { name: 'Message Simple Fill', icon: MessageSimpleFillIcon },
  { name: 'Message Simple New', icon: MessageSimpleNewIcon },
  { name: 'Messenger', icon: MessengerIcon },
  { name: 'Messenger Fill', icon: MessengerFillIcon },
  { name: 'Minus', icon: MinusIcon },
  { name: 'Minus Fill', icon: MinusFillIcon },
  { name: 'Moon', icon: MoonIcon },
  { name: 'Moon Fill', icon: MoonFillIcon },
  { name: 'More', icon: MoreIcon },
  { name: 'More Fill', icon: MoreFillIcon },
  { name: 'Mute', icon: MuteIcon },
  { name: 'Notification', icon: NotificationIcon },
  { name: 'Notification Fill', icon: NotificationFillIcon },
  { name: 'Payment', icon: PaymentIcon },
  { name: 'Payment Docs', icon: PaymentDocsIcon },
  { name: 'Payment Transfer', icon: PaymentTransferIcon },
  { name: 'Person', icon: PersonIcon },
  { name: 'Person Card', icon: PersonCardIcon },
  { name: 'Phone', icon: PhoneIcon },
  { name: 'Phone Bolt', icon: PhoneBoltIcon },
  { name: 'Phone Vibrate', icon: PhoneVibrateIcon },
  { name: 'Photo', icon: PhotoIcon },
  { name: 'Photo Fill', icon: PhotoFillIcon },
  { name: 'Pin', icon: PinIcon },
  { name: 'Pin Fill', icon: PinFillIcon },
  { name: 'Plus', icon: PlusIcon },
  { name: 'Plus Fill', icon: PlusFillIcon },
  { name: 'PositionBottom', icon: PositionBottomIcon },
  { name: 'PositionBottomLeft', icon: PositionBottomLeftIcon },
  { name: 'PositionBottomRight', icon: PositionBottomRightIcon },
  { name: 'PositionCenter', icon: PositionCenterIcon },
  { name: 'PositionLeft', icon: PositionLeftIcon },
  { name: 'PositionRight', icon: PositionRightIcon },
  { name: 'PositionTop', icon: PositionTopIcon },
  { name: 'PositionTopLeft', icon: PositionTopLeftIcon },
  { name: 'PositionTopRight', icon: PositionTopRightIcon },
  { name: 'Post', icon: PostIcon },
  { name: 'Post Cancel', icon: PostCancelIcon },
  { name: 'Post Fill', icon: PostFillIcon },
  { name: 'Private', icon: PrivateIcon },
  { name: 'Private Outline', icon: PrivateOutlineIcon },
  { name: 'Private Unlocked', icon: PrivateUnlockedIcon },
  { name: 'Profile', icon: ProfileIcon },
  { name: 'Profile Fill', icon: ProfileFillIcon },
  { name: 'Quote', icon: QuoteIcon },
  { name: 'Relaxed', icon: RelaxedIcon },
  { name: 'Rep', icon: RepIcon },
  { name: 'Reply', icon: ReplyIcon },
  { name: 'Right Caret', icon: RightCaretIcon },
  { name: 'Rss', icon: RssIcon },
  { name: 'Sad', icon: SadIcon },
  { name: 'Sam', icon: SamIcon },
  { name: 'Search', icon: SearchIcon },
  { name: 'Send', icon: SendIcon },
  { name: 'Send Fill', icon: SendFillIcon },
  { name: 'Settings', icon: SettingsIcon },
  { name: 'Share', icon: ShareIcon },
  { name: 'Shirt', icon: ShirtIcon },
  { name: 'Shirt Fill', icon: ShirtFillIcon },
  { name: 'Slack', icon: SlackIcon },
  { name: 'Slack Fill', icon: SlackFillIcon },
  { name: 'SortAsc', icon: SortAscIcon },
  { name: 'SortDesc', icon: SortDescIcon },
  { name: 'Sticker', icon: StickerIcon },
  { name: 'Support', icon: SupportIcon },
  { name: 'Support Fill', icon: SupportFillIcon },
  { name: 'Terminal', icon: TerminalIcon },
  { name: 'Thread', icon: ThreadIcon },
  { name: 'Thumbs Down', icon: ThumbsDownIcon },
  { name: 'Thumbs Down Fill', icon: ThumbsDownFillIcon },
  { name: 'Thumbs Up', icon: ThumbsUpIcon },
  { name: 'Thumbs Up Fill', icon: ThumbsUpFillIcon },
  { name: 'Transactions', icon: TransactionsIcon },
  { name: 'Tv', icon: TvIcon },
  { name: 'Tv Fill', icon: TvFillIcon },
  { name: 'Twitch', icon: TwitchIcon },
  { name: 'TwitchNude', icon: TwitchNudeIcon },
  { name: 'Twitch Fill', icon: TwitchFillIcon },
  { name: 'Twitter', icon: TwitterIcon },
  { name: 'Twitter Fill', icon: TwitterFillIcon },
  { name: 'Up', icon: UpIcon },
  { name: 'Up Caret', icon: UpCaretIcon },
  { name: 'Up Fill', icon: UpFillIcon },
  { name: 'View', icon: ViewIcon },
  { name: 'View Back', icon: ViewBackIcon },
  { name: 'View Close', icon: ViewCloseIcon },
  { name: 'View Close Small', icon: ViewCloseSmallIcon },
  { name: 'View Fill', icon: ViewFillIcon },
  { name: 'View Forward', icon: ViewForwardIcon },
  { name: 'View Hide', icon: ViewHideIcon },
  { name: 'View Reload', icon: ViewReloadIcon },
  { name: 'Web', icon: WebIcon },
  { name: 'Welcome', icon: WelcomeIcon },
  { name: 'Wifi', icon: WifiIcon },
  { name: 'X', icon: XIcon },
  { name: 'X Fill', icon: XFillIcon },
  { name: 'Youtube', icon: YoutubeIcon },
  { name: 'Youtube Fill', icon: YoutubeFillIcon },
  { name: 'Zoom In', icon: ZoomInIcon },
  { name: 'Zoom Out', icon: ZoomOutIcon },
]
